#!/bin/bash --login
#SBATCH -J Deepmd_mixed
#SBATCH -N 1
#SBATCH -n 10
#SBATCH --gres=gpu:h200:1
#SBATCH --time=4:00:00
#SBATCH --mem=128G

ml purge
ml Miniforge3
conda activate heat
which python3
which python
unset PYTHONPATH
python3 train.py --sigma_start ${1} --sigma_method fixed



